const TARGET=32561;
const SOURCES={local:'data/vn-items.json',remote:'https://raw.githubusercontent.com/CroMarmot/nikkiup2u3/gh-pages/data/wardrobe.json'};
const A=['Đơn giản','Hoa lệ','Năng động','Dễ thương','Thanh lịch','Trong sáng','Gợi cảm','Trưởng thành','Mát mẻ','Ấm áp'];
const VI={'发型':'Tóc','连衣裙':'Váy','外套':'Áo khoác','上衣':'Áo','下装':'Quần','袜子':'Tất','鞋子':'Giày','饰品':'Phụ kiện','妆容':'Trang điểm','萤光之灵':'Linh hồn ánh sáng'};
const C=['Tất cả','Tóc','Váy','Áo khoác','Áo','Quần','Tất','Giày','Phụ kiện','Trang điểm'];
const state={items:[],q:'',cat:'Tất cả',rarity:'Tất cả',sort:'score',owned:new Set(JSON.parse(localStorage.getItem('nstt-owned')||'[]')),page:0,tab:'all'};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function layout(){app.innerHTML=`<div class="app"><header class="top"><div class="topin"><div class="brand"><div class="mark">✦</div><div><b>NSTT Việt</b><span>Ngôi Sao Thời Trang · VNG</span></div></div><nav class="nav"><button class="active" data-tab="all">Kho đồ</button><button data-tab="rank">Bảng xếp hạng</button><button data-tab="about">Giới thiệu</button></nav><button class="iconbtn" id="theme">☾</button></div></header><div class="wrap"><div id="view"></div><div class="footer">NSTT Việt · fan-made · không phải website chính thức của VNG.</div></div><nav class="mobileNav"><button class="active" data-tab="all"><span>✦</span>Kho đồ</button><button data-tab="rank"><span>♛</span>Xếp hạng</button><button data-tab="about"><span>ⓘ</span>Giới thiệu</button></nav></div>`}
function score(x){const vals=x.attrs.map(v=>({S:4,SS:5,A:3,B:2,C:1,D:0}[v]??0));return vals.reduce((a,b)=>a+b,0)*10+(Number(x.rarity)||0)*20}
function normalize(r,i){return{id:String(r[2]||i),name:String(r[0]||'Chưa có tên'),vi:VI[r[1]]||String(r[1]||''),rarity:Number(r[3])||0,attrs:r.slice(4,14),tags:String(r[14]||'').split(',').map(s=>s.trim()).filter(Boolean),source:String(r[15]||''),set:String(r[16]||'')}}
function filter(){let a=state.items.filter(x=>{const q=state.q.toLowerCase();return(!q||[x.name,x.id,x.vi,x.set,x.source,x.tags.join(' ')].join(' ').toLowerCase().includes(q))&&(state.cat==='Tất cả'||x.vi===state.cat)&&(state.rarity==='Tất cả'||x.rarity===+state.rarity)});if(state.sort==='score')a.sort((a,b)=>score(b)-score(a));else if(state.sort==='rarity')a.sort((a,b)=>b.rarity-a.rarity||score(b)-score(a));else if(state.sort==='name')a.sort((a,b)=>a.name.localeCompare(b.name));else a.sort((a,b)=>Number(a.id)-Number(b.id));return a}
function card(x,i){return `<article class="card" data-id="${esc(x.id)}"><button class="heart" data-own="${esc(x.id)}">${state.owned.has(x.id)?'♥':'♡'}</button><div class="visual"><span class="letter">${esc((x.name||'✦')[0])}</span><span class="rank">#${i+1}</span></div><div class="body"><div class="name">${esc(x.name)}</div><div class="meta">${esc(x.vi)} · ID ${esc(x.id)}</div><div class="badges"><span class="badge stars">${'★'.repeat(Math.min(5,x.rarity))}</span><span class="badge">${score(x)} điểm</span></div></div></article>`}
function hero(){return `<section class="hero"><div class="heroMain"><div class="eyebrow">NGÔI SAO THỜI TRANG · BẢN VIỆT</div><h1>Kho item<br><span style="color:var(--rose)">32.561 món đồ.</span></h1><p>Tra cứu, lọc và xếp hạng item theo điểm thuộc tính. Giao diện tối ưu cho người chơi Việt, chạy trực tiếp trên GitHub Pages.</p><div class="search"><input id="search" value="${esc(state.q)}" placeholder="Tìm tên item, ID, tag…"><button id="go">Tìm</button></div></div><div class="heroSide"><div class="feature"><div><div class="num">${TARGET.toLocaleString('vi-VN')}</div><small>mục tiêu dữ liệu</small></div><strong>ITEM DATABASE ↗</strong></div><div class="feature"><div><div class="num">${state.items.length.toLocaleString('vi-VN')}</div><small>item đã nạp</small></div><strong>${state.items.length===TARGET?'Đủ 32.561 item':'Cần đồng bộ dữ liệu'}</strong></div><div class="feature"><div><div class="num">${state.owned.size}</div><small>món trong tủ</small></div><strong>Tủ của tôi ♡</strong></div></div></section>`}
function catalogue(){const a=filter(),end=(state.page+1)*60;document.getElementById('view').innerHTML=hero()+`<section class="section"><div class="sectionHead"><div><div class="eyebrow">DATABASE</div><h2>Kho & xếp hạng item</h2><p>${a.length.toLocaleString('vi-VN')} kết quả · sắp xếp theo ${state.sort==='score'?'điểm tổng':state.sort==='rarity'?'độ hiếm':state.sort==='name'?'tên':'ID'}</p></div></div><div class="chips">${C.map(c=>`<button class="chip ${state.cat===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="toolbar"><select id="rarity"><option value="Tất cả">Tất cả độ hiếm</option>${[5,4,3,2,1].map(n=>`<option value="${n}" ${String(state.rarity)===String(n)?'selected':''}>${n}★</option>`).join('')}</select><select id="sort"><option value="score" ${state.sort==='score'?'selected':''}>Điểm tổng ↓</option><option value="rarity" ${state.sort==='rarity'?'selected':''}>Độ hiếm ↓</option><option value="name" ${state.sort==='name'?'selected':''}>Tên A → Z</option><option value="id" ${state.sort==='id'?'selected':''}>ID tăng dần</option></select><button class="chip" id="clear">Xoá lọc</button><span class="result">${TARGET.toLocaleString('vi-VN')} mục tiêu</span></div>${state.items.length!==TARGET?`<div class="notice">⚠️ Hiện kho đang có <b>${state.items.length.toLocaleString('vi-VN')}</b> item từ nguồn dữ liệu dự phòng. Để xếp hạng đúng 32.561 item bản Việt, hãy đặt file dữ liệu Việt tại <code>data/vn-items.json</code>.</div>`:''}<div class="grid">${a.slice(0,end).map((x,i)=>card(x,i)).join('')}</div>${end<a.length?`<div style="text-align:center;padding:28px"><button class="primary" id="more">Xem thêm 60</button></div>`:''}</section>`;bind()}
function rank(){const a=filter().slice(0,20);document.getElementById('view').innerHTML=`<section class="hero"><div class="heroMain"><div class="eyebrow">TOP 20</div><h1>Bảng xếp hạng<br><span style="color:var(--rose)">item nổi bật.</span></h1><p>Thứ hạng được tính từ độ hiếm và tổng điểm thuộc tính của dữ liệu đang nạp. Đây là bảng xếp hạng kỹ thuật, không phải đánh giá chính thức trong game.</p></div><div class="heroSide"><div class="feature"><div><div class="num">20</div><small>vị trí hiển thị</small></div><strong>TOP ITEM ↗</strong></div></div></section><section class="section"><div class="stagegrid">${a.map((x,i)=>`<div class="stagebox" style="display:flex;align-items:center;gap:15px"><b style="font-size:24px;width:42px">${String(i+1).padStart(2,'0')}</b><div style="flex:1"><b>${esc(x.name)}</b><p style="margin:5px 0 0">${esc(x.vi)} · ${'★'.repeat(x.rarity)} · ID ${esc(x.id)}</p></div><strong>${score(x)} điểm</strong></div>`).join('')}</div></section>`;bindTabs()}
function about(){document.getElementById('view').innerHTML=`<section class="hero"><div class="heroMain"><div class="eyebrow">FAN-MADE</div><h1>Một kho item<br><span style="color:var(--rose)">cho người Việt.</span></h1><p>Nguồn cộng đồng Annie Nikki Homes hiện công khai con số 32.561 trang phục. Website này được làm riêng với mục tiêu tạo giao diện tra cứu/xếp hạng khác, không sao chép giao diện.</p></div><div class="heroSide"><div class="feature"><div><div class="num">32.561</div><small>con số tham chiếu</small></div><strong>Dữ liệu cộng đồng</strong></div></div></section><section class="section"><div class="stagegrid"><div class="stagebox"><b>Minh bạch dữ liệu</b><p>Ứng dụng báo rõ số item thực tế đang nạp. Không giả mạo 32.561 item khi file dữ liệu chưa đủ.</p></div><div class="stagebox"><b>Xếp hạng</b><p>Điểm được tính từ độ hiếm và các cấp S/SS/A/B/C/D có trong dữ liệu.</p></div><div class="stagebox"><b>Bản Việt</b><p>File dữ liệu cuối cùng nên là dữ liệu đúng server VNG Việt Nam, có tên item, loại, sao và chỉ số.</p></div></div></section>`;bindTabs()}
function toggle(id){state.owned.has(id)?state.owned.delete(id):state.owned.add(id);localStorage.setItem('nstt-owned',JSON.stringify([...state.owned]));render()}
function openItem(id){const x=state.items.find(i=>i.id===id);if(!x)return;const d=document.createElement('div');d.className='drawer show';d.innerHTML=`<div class="modal"><div class="modalTop"><div><div class="eyebrow">ITEM #${esc(x.id)}</div><h2 style="font:600 34px 'Playfair Display';margin:8px 0">${esc(x.name)}</h2><div style="color:var(--muted)">${esc(x.vi)} · ${'★'.repeat(x.rarity)} · ${score(x)} điểm</div></div><button class="close">Đóng</button></div><div class="attrs">${x.attrs.map((v,i)=>`<div class="attr"><span>${A[i]}</span><b>${esc(v||'—')}</b></div>`).join('')}</div><div class="stagegrid"><div class="stagebox"><b>Tag</b><p>${esc(x.tags.join(' · ')||'—')}</p></div><div class="stagebox"><b>Nguồn</b><p>${esc(x.source||'—')}</p></div><div class="stagebox"><b>Bộ</b><p>${esc(x.set||'—')}</p></div></div><button class="primary" style="margin-top:15px">${state.owned.has(x.id)?'♥ Đã có trong tủ':'♡ Thêm vào tủ'}</button></div>`;document.body.appendChild(d);d.querySelector('.close').onclick=()=>d.remove();d.querySelector('.primary').onclick=()=>{toggle(x.id);d.remove()}}
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()})}
function bind(){bindTabs();document.getElementById('go').onclick=()=>{state.q=document.getElementById('search').value.trim();state.page=0;catalogue()};document.getElementById('search').onkeydown=e=>{if(e.key==='Enter')document.getElementById('go').click()};document.getElementById('rarity').onchange=e=>{state.rarity=e.target.value;state.page=0;catalogue()};document.getElementById('sort').onchange=e=>{state.sort=e.target.value;state.page=0;catalogue()};document.getElementById('clear').onclick=()=>{state.q='';state.cat='Tất cả';state.rarity='Tất cả';state.sort='score';state.page=0;catalogue()};document.getElementById('more')?.addEventListener('click',()=>{state.page++;catalogue()});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;state.page=0;catalogue()});document.querySelectorAll('[data-id]').forEach(e=>e.onclick=ev=>{if(!ev.target.closest('[data-own]'))openItem(e.dataset.id)});document.querySelectorAll('[data-own]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggle(b.dataset.own)})}
function render(){if(state.tab==='rank')rank();else if(state.tab==='about')about();else catalogue();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab))}
async function load(){layout();try{const r=await fetch(SOURCES.local,{cache:'no-store'});if(r.ok){const j=await r.json();state.items=Array.isArray(j.items)?j.items:Array.isArray(j)?j.map(normalize):[]}}catch(e){}if(!state.items.length){try{const j=await fetch(SOURCES.remote).then(r=>r.json());state.items=j.map(normalize)}catch(e){}}render()}
load();